/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DepthfoldRouteImport } from './routes/depthfold'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments.$slug'

const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DepthfoldRoute = DepthfoldRouteImport.update({
  id: '/depthfold',
  path: '/depthfold',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TreatmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/depthfold': typeof DepthfoldRoute
  '/gallery': typeof GalleryRoute
  '/resources': typeof ResourcesRoute
  '/testimonials': typeof TestimonialsRoute
  '/treatments': typeof TreatmentsRouteWithChildren
  '/treatments/$slug': typeof TreatmentsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/depthfold': typeof DepthfoldRoute
  '/gallery': typeof GalleryRoute
  '/resources': typeof ResourcesRoute
  '/testimonials': typeof TestimonialsRoute
  '/treatments': typeof TreatmentsRouteWithChildren
  '/treatments/$slug': typeof TreatmentsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/depthfold': typeof DepthfoldRoute
  '/gallery': typeof GalleryRoute
  '/resources': typeof ResourcesRoute
  '/testimonials': typeof TestimonialsRoute
  '/treatments': typeof TreatmentsRouteWithChildren
  '/treatments/$slug': typeof TreatmentsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/depthfold'
    | '/gallery'
    | '/resources'
    | '/testimonials'
    | '/treatments'
    | '/treatments/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/depthfold'
    | '/gallery'
    | '/resources'
    | '/testimonials'
    | '/treatments'
    | '/treatments/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/depthfold'
    | '/gallery'
    | '/resources'
    | '/testimonials'
    | '/treatments'
    | '/treatments/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DepthfoldRoute: typeof DepthfoldRoute
  GalleryRoute: typeof GalleryRoute
  ResourcesRoute: typeof ResourcesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TreatmentsRoute: typeof TreatmentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depthfold': {
      id: '/depthfold'
      path: '/depthfold'
      fullPath: '/depthfold'
      preLoaderRoute: typeof DepthfoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof TreatmentsRoute
    }
  }
}

interface TreatmentsRouteChildren {
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
}

const TreatmentsRouteChildren: TreatmentsRouteChildren = {
  TreatmentsSlugRoute: TreatmentsSlugRoute,
}

const TreatmentsRouteWithChildren = TreatmentsRoute._addFileChildren(
  TreatmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DepthfoldRoute: DepthfoldRoute,
  GalleryRoute: GalleryRoute,
  ResourcesRoute: ResourcesRoute,
  TestimonialsRoute: TestimonialsRoute,
  TreatmentsRoute: TreatmentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
